INSERT INTO Operations_Types VALUES
(1,'COMPRA A VISTA')
ON CONFLICT DO NOTHING;

INSERT INTO Operations_Types VALUES
(2,'COMPRA PARCELADA')
ON CONFLICT DO NOTHING;

INSERT INTO Operations_Types VALUES
(3,'SAQUE')
ON CONFLICT DO NOTHING;

INSERT INTO Operations_Types VALUES
(4,'PAGAMENTO')
ON CONFLICT DO NOTHING;


